// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HousingHubBackend.Models;

[Table("Amenity")]
public partial class Amenity
{
    [Key]
    public int AmenityId { get; set; }

    public int? SocietyId { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    public double? HourlyRate { get; set; }

    public int? MaxCapacity { get; set; }

    public TimeOnly? OpeningTime { get; set; }

    public TimeOnly? ClosingTime { get; set; }

    [InverseProperty("Amenity")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("SocietyId")]
    [InverseProperty("Amenities")]
    public virtual Society Society { get; set; }
}