// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HousingHubBackend.Models;

[Table("AnnouncementTargetWing")]
public partial class AnnouncementTargetWing
{
    [Key]
    [Column("ATWId")]
    public int Atwid { get; set; }

    public int? AnnouncementId { get; set; }

    public int? WingId { get; set; }

    [ForeignKey("AnnouncementId")]
    [InverseProperty("AnnouncementTargetWings")]
    public virtual Announcement Announcement { get; set; }

    [ForeignKey("WingId")]
    [InverseProperty("AnnouncementTargetWings")]
    public virtual Wing Wing { get; set; }
}