// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HousingHubBackend.Models;

[Table("AnnouncementTargetFlat")]
public partial class AnnouncementTargetFlat
{
    [Key]
    [Column("ATFId")]
    public int Atfid { get; set; }

    public int? AnnouncementId { get; set; }

    public int? FlatId { get; set; }

    [ForeignKey("AnnouncementId")]
    [InverseProperty("AnnouncementTargetFlats")]
    public virtual Announcement Announcement { get; set; }

    [ForeignKey("FlatId")]
    [InverseProperty("AnnouncementTargetFlats")]
    public virtual Flat Flat { get; set; }
}