// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HousingHubBackend.Models;

[Table("Announcement")]
[Index("SocietyId", Name = "IX_Announcement_SocietyId")]
public partial class Announcement
{
    [Key]
    [Column("AId")]
    public int Aid { get; set; }

    [StringLength(200)]
    public string Title { get; set; }

    public string Content { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public int? SocietyId { get; set; }

    [Column("isGlobal")]
    public bool? IsGlobal { get; set; }

    [InverseProperty("Announcement")]
    public virtual ICollection<AnnouncementTargetFlat> AnnouncementTargetFlats { get; set; } = new List<AnnouncementTargetFlat>();

    [InverseProperty("Announcement")]
    public virtual ICollection<AnnouncementTargetWing> AnnouncementTargetWings { get; set; } = new List<AnnouncementTargetWing>();

    [ForeignKey("CreatedBy")]
    [InverseProperty("Announcements")]
    public virtual UserAccount CreatedByNavigation { get; set; }

    [ForeignKey("SocietyId")]
    [InverseProperty("Announcements")]
    public virtual Society Society { get; set; }
}