// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HousingHubBackend.Models;

[Table("Booking")]
[Index("Status", Name = "IX_Booking_Status")]
public partial class Booking
{
    [Key]
    public int BookingId { get; set; }

    public int? UserId { get; set; }

    public int? FlatId { get; set; }

    public int? AmenityId { get; set; }

    public DateOnly? CreatedAt { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public double? Amount { get; set; }

    public bool? Paid { get; set; }

    [StringLength(100)]
    public string TransactionId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Status { get; set; }

    [ForeignKey("AmenityId")]
    [InverseProperty("Bookings")]
    public virtual Amenity Amenity { get; set; }

    [ForeignKey("FlatId")]
    [InverseProperty("Bookings")]
    public virtual Flat Flat { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Bookings")]
    public virtual UserAccount User { get; set; }
}