// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HousingHubBackend.Models;

[Table("Complaint")]
[Index("Status", Name = "IX_Complaint_Status")]
public partial class Complaint
{
    [Key]
    public int ComplaintId { get; set; }

    public int? FlatId { get; set; }

    public int? RaisedBy { get; set; }

    [StringLength(100)]
    public string Title { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    [StringLength(50)]
    public string Category { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ResolvedAt { get; set; }

    [ForeignKey("FlatId")]
    [InverseProperty("Complaints")]
    public virtual Flat Flat { get; set; }

    [ForeignKey("RaisedBy")]
    [InverseProperty("Complaints")]
    public virtual UserAccount RaisedByNavigation { get; set; }
}