// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HousingHubBackend.Models;

[Table("Flat")]
public partial class Flat
{
    [Key]
    public int FlatId { get; set; }

    public int? WingId { get; set; }

    [StringLength(20)]
    public string FlatNumber { get; set; }

    [StringLength(20)]
    public string FloorNumber { get; set; }

    public double? Area { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Status { get; set; }

    [InverseProperty("Flat")]
    public virtual ICollection<AnnouncementTargetFlat> AnnouncementTargetFlats { get; set; } = new List<AnnouncementTargetFlat>();

    [InverseProperty("Flat")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [InverseProperty("Flat")]
    public virtual ICollection<Complaint> Complaints { get; set; } = new List<Complaint>();

    [InverseProperty("Flat")]
    public virtual ICollection<MaintenanceBill> MaintenanceBills { get; set; } = new List<MaintenanceBill>();

    [InverseProperty("Flat")]
    public virtual ICollection<UserAccount> UserAccounts { get; set; } = new List<UserAccount>();

    [InverseProperty("Flat")]
    public virtual ICollection<Visitor> Visitors { get; set; } = new List<Visitor>();

    [ForeignKey("WingId")]
    [InverseProperty("Flats")]
    public virtual Wing Wing { get; set; }
}