// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HousingHubBackend.Models;

[Table("MaintenanceFee")]
public partial class MaintenanceFee
{
    [Key]
    [Column("MFId")]
    public int Mfid { get; set; }

    public int? WingId { get; set; }

    public double? RatePerSqft { get; set; }

    public DateOnly? EffectiveFrom { get; set; }

    public DateOnly? EffectiveTo { get; set; }

    [Column("is_active")]
    public bool? IsActive { get; set; }

    public int? CreatedBy { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("MaintenanceFees")]
    public virtual UserAccount CreatedByNavigation { get; set; }

    [InverseProperty("MaintenanceFee")]
    public virtual ICollection<MaintenanceBill> MaintenanceBills { get; set; } = new List<MaintenanceBill>();

    [ForeignKey("WingId")]
    [InverseProperty("MaintenanceFees")]
    public virtual Wing Wing { get; set; }
}