// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HousingHubBackend.Models;

[Table("MaintenanceBill")]
public partial class MaintenanceBill
{
    [Key]
    [Column("MBId")]
    public int Mbid { get; set; }

    public int? FlatId { get; set; }

    public int? Mfid { get; set; }

    public DateOnly? PeriodStart { get; set; }

    public DateOnly? PeriodEnd { get; set; }

    public DateOnly? DueDate { get; set; }

    public double? Amount { get; set; }

    public DateOnly? PaidDate { get; set; }

    public bool? Paid { get; set; }

    [StringLength(100)]
    public string TransactionId { get; set; }

    [ForeignKey("FlatId")]
    [InverseProperty("MaintenanceBills")]
    public virtual Flat Flat { get; set; }

    [ForeignKey("Mfid")]
    [InverseProperty("MaintenanceBills")]
    public virtual MaintenanceFee MaintenanceFee { get; set; }
}