// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HousingHubBackend.Models;

[Table("Society")]
public partial class Society
{
    [Key]
    public int SocietyId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(255)]
    public string Address { get; set; }

    [StringLength(50)]
    public string State { get; set; }

    [StringLength(50)]
    public string Country { get; set; }

    [StringLength(50)]
    public string City { get; set; }

    public int? Pincode { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    public bool? IsVerified { get; set; }

    [InverseProperty("Society")]
    public virtual ICollection<Amenity> Amenities { get; set; } = new List<Amenity>();

    [InverseProperty("Society")]
    public virtual ICollection<Announcement> Announcements { get; set; } = new List<Announcement>();

    [InverseProperty("Society")]
    public virtual ICollection<UserAccount> UserAccounts { get; set; } = new List<UserAccount>();

    [InverseProperty("Society")]
    public virtual ICollection<Wing> Wings { get; set; } = new List<Wing>();
}