// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HousingHubBackend.Models;

[Table("UserAccount")]
[Index("Role", Name = "IX_User_Role")]
[Index("SocietyId", Name = "IX_User_SocietyId")]
[Index("Email", Name = "UQ__UserAcco__A9D10534881C3379", IsUnique = true)]
public partial class UserAccount
{
    [Key]
    public int UserId { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    [StringLength(200)]
    public string Password { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Role { get; set; }

    public int? SocietyId { get; set; }

    public int? FlatId { get; set; }

    public bool? IsVerified { get; set; }

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Announcement> Announcements { get; set; } = new List<Announcement>();

    [InverseProperty("User")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [InverseProperty("RaisedByNavigation")]
    public virtual ICollection<Complaint> Complaints { get; set; } = new List<Complaint>();

    [ForeignKey("FlatId")]
    [InverseProperty("UserAccounts")]
    public virtual Flat Flat { get; set; }

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<MaintenanceFee> MaintenanceFees { get; set; } = new List<MaintenanceFee>();

    [ForeignKey("SocietyId")]
    [InverseProperty("UserAccounts")]
    public virtual Society Society { get; set; }

    [InverseProperty("RecordedByNavigation")]
    public virtual ICollection<Visitor> Visitors { get; set; } = new List<Visitor>();
}