// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HousingHubBackend.Models;

[Table("Visitor")]
public partial class Visitor
{
    [Key]
    public int VisitorId { get; set; }

    public int? FlatId { get; set; }

    [StringLength(100)]
    public string Name { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string VisitorType { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    [StringLength(50)]
    public string VehicleNo { get; set; }

    [StringLength(100)]
    public string Purpose { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EntryTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ExitTime { get; set; }

    public int? RecordedBy { get; set; }

    [ForeignKey("FlatId")]
    [InverseProperty("Visitors")]
    public virtual Flat Flat { get; set; }

    [ForeignKey("RecordedBy")]
    [InverseProperty("Visitors")]
    public virtual UserAccount RecordedByNavigation { get; set; }
}