// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HousingHubBackend.Models;

[Table("Wing")]
public partial class Wing
{
    [Key]
    public int WingId { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    public int? TotalFloors { get; set; }

    public int? FlatsPerFloor { get; set; }

    public int? SocietyId { get; set; }

    [InverseProperty("Wing")]
    public virtual ICollection<AnnouncementTargetWing> AnnouncementTargetWings { get; set; } = new List<AnnouncementTargetWing>();

    [InverseProperty("Wing")]
    public virtual ICollection<Flat> Flats { get; set; } = new List<Flat>();

    [InverseProperty("Wing")]
    public virtual ICollection<MaintenanceFee> MaintenanceFees { get; set; } = new List<MaintenanceFee>();

    [ForeignKey("SocietyId")]
    [InverseProperty("Wings")]
    public virtual Society Society { get; set; }
}